version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: survayapp-mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${MYSQL_HOST_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../till.mezoo.co.il_bm1756763301dm/fresh.sql:/docker-entrypoint-initdb.d/00_fresh.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mysql_data:


